using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Icu
{
	public enum DateFormatField
	{
		UDAT_ERA_FIELD = 0,

		UDAT_YEAR_FIELD = 1,

		UDAT_MONTH_FIELD = 2,

		UDAT_DATE_FIELD = 3,

		UDAT_HOUR_OF_DAY1_FIELD = 4,

		UDAT_HOUR_OF_DAY0_FIELD = 5,

		UDAT_MINUTE_FIELD = 6,

		UDAT_SECOND_FIELD = 7,

		UDAT_FRACTIONAL_SECOND_FIELD = 8,

		UDAT_DAY_OF_WEEK_FIELD = 9,

		UDAT_DAY_OF_YEAR_FIELD = 10,

		UDAT_DAY_OF_WEEK_IN_MONTH_FIELD = 11,

		UDAT_WEEK_OF_YEAR_FIELD = 12,

		UDAT_WEEK_OF_MONTH_FIELD = 13,

		UDAT_AM_PM_FIELD = 14,

		UDAT_HOUR1_FIELD = 15,

		UDAT_HOUR0_FIELD = 16,

		UDAT_TIMEZONE_FIELD = 17,

		UDAT_YEAR_WOY_FIELD = 18,

		UDAT_DOW_LOCAL_FIELD = 19,

		UDAT_EXTENDED_YEAR_FIELD = 20,

		UDAT_JULIAN_DAY_FIELD = 21,

		UDAT_MILLISECONDS_IN_DAY_FIELD = 22,

		UDAT_TIMEZONE_RFC_FIELD = 23,

		UDAT_TIMEZONE_GENERIC_FIELD = 24,
		UDAT_STANDALONE_DAY_FIELD = 25,

		UDAT_STANDALONE_MONTH_FIELD = 26,

		UDAT_QUARTER_FIELD = 27,

		UDAT_STANDALONE_QUARTER_FIELD = 28,

		UDAT_TIMEZONE_SPECIAL_FIELD = 29,

		UDAT_YEAR_NAME_FIELD = 30,

		UDAT_TIMEZONE_LOCALIZED_GMT_OFFSET_FIELD = 31,

		UDAT_TIMEZONE_ISO_FIELD = 32,

		UDAT_TIMEZONE_ISO_LOCAL_FIELD = 33,
		
		UDAT_AM_PM_MIDNIGHT_NOON_FIELD = 35,

		/* FieldPosition selector for 'B' field alignment.
		 * Displays flexible day periods, such as "in the morning", if available.
		 * @stable ICU 57
		 */
		UDAT_FLEXIBLE_DAY_PERIOD_FIELD = 36,
	};
}
