using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Icu
{
	public enum DateFormatSymbolType
	{
		UDAT_ERAS,
		UDAT_MONTHS,
		UDAT_SHORT_MONTHS,
		UDAT_WEEKDAYS,
		UDAT_SHORT_WEEKDAYS,
		UDAT_AM_PMS,
		UDAT_LOCALIZED_CHARS,
		UDAT_ERA_NAMES,
		UDAT_NARROW_MONTHS,
		UDAT_NARROW_WEEKDAYS,
		UDAT_STANDALONE_MONTHS,
		UDAT_STANDALONE_SHORT_MONTHS,
		UDAT_STANDALONE_NARROW_MONTHS,
		UDAT_STANDALONE_WEEKDAYS,
		UDAT_STANDALONE_SHORT_WEEKDAYS,
		UDAT_STANDALONE_NARROW_WEEKDAYS,
		UDAT_QUARTERS,
		UDAT_SHORT_QUARTERS,
		UDAT_STANDALONE_QUARTERS,
		UDAT_STANDALONE_SHORT_QUARTERS,
		UDAT_SHORTER_WEEKDAYS,
		UDAT_STANDALONE_SHORTER_WEEKDAYS,
		UDAT_CYCLIC_YEARS_WIDE,
		UDAT_CYCLIC_YEARS_ABBREVIATED,
		UDAT_CYCLIC_YEARS_NARROW,
		UDAT_ZODIAC_NAMES_WIDE,
		UDAT_ZODIAC_NAMES_ABBREVIATED,
		UDAT_ZODIAC_NAMES_NARROW
	}
}
