using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Icu
{
	public enum DisplayContextType
	{
		UDISPCTX_TYPE_DIALECT_HANDLING = 0,
		UDISPCTX_TYPE_CAPITALIZATION = 1,
		UDISPCTX_TYPE_DISPLAY_LENGTH = 2,
		UDISPCTX_TYPE_SUBSTITUTE_HANDLING = 3
	};

	public enum DisplayContext
	{
		UDISPCTX_STANDARD_NAMES = (DisplayContextType.UDISPCTX_TYPE_DIALECT_HANDLING << 8) + 0,
		UDISPCTX_DIALECT_NAMES = (DisplayContextType.UDISPCTX_TYPE_DIALECT_HANDLING << 8) + 1,
		UDISPCTX_CAPITALIZATION_NONE = (DisplayContextType.UDISPCTX_TYPE_CAPITALIZATION << 8) + 0,
		UDISPCTX_CAPITALIZATION_FOR_MIDDLE_OF_SENTENCE = (DisplayContextType.UDISPCTX_TYPE_CAPITALIZATION << 8) + 1,
		UDISPCTX_CAPITALIZATION_FOR_BEGINNING_OF_SENTENCE = (DisplayContextType.UDISPCTX_TYPE_CAPITALIZATION << 8) + 2,
		UDISPCTX_CAPITALIZATION_FOR_UI_LIST_OR_MENU = (DisplayContextType.UDISPCTX_TYPE_CAPITALIZATION << 8) + 3,
		UDISPCTX_CAPITALIZATION_FOR_STANDALONE = (DisplayContextType.UDISPCTX_TYPE_CAPITALIZATION << 8) + 4,
		UDISPCTX_LENGTH_FULL = (DisplayContextType.UDISPCTX_TYPE_DISPLAY_LENGTH << 8) + 0,
		UDISPCTX_LENGTH_SHORT = (DisplayContextType.UDISPCTX_TYPE_DISPLAY_LENGTH << 8) + 1,
		UDISPCTX_SUBSTITUTE = (DisplayContextType.UDISPCTX_TYPE_SUBSTITUTE_HANDLING << 8) + 0,
		UDISPCTX_NO_SUBSTITUTE = (DisplayContextType.UDISPCTX_TYPE_SUBSTITUTE_HANDLING << 8) + 1

	};
}
